export const employees = [
  {
    id: 1,
    firstName: "Alice",
    lastName: "Morgan",
    email: "alice.morgan@fakemail.com",
    department: "Engineering",
    role: "Frontend Developer",
    empProfile: "https://i.pravatar.cc/150?img=1",
  },
  {
    id: 2,
    firstName: "Ben",
    lastName: "Thompson",
    email: "ben.thompson@fakemail.com",
    department: "Marketing",
    role: "Content Strategist",
    empProfile: "https://i.pravatar.cc/150?img=2",
  },
  {
    id: 3,
    firstName: "Catherine",
    lastName: "Lee",
    email: "catherine.lee@fakemail.com",
    department: "HR",
    role: "HR Manager",
    empProfile: "https://i.pravatar.cc/150?img=3",
  },
  {
    id: 4,
    firstName: "Daniel",
    lastName: "Woods",
    email: "daniel.woods@fakemail.com",
    department: "Finance",
    role: "Accountant",
    empProfile: "https://i.pravatar.cc/150?img=4",
  },
  {
    id: 5,
    firstName: "Eva",
    lastName: "Garcia",
    email: "eva.garcia@fakemail.com",
    department: "Product",
    role: "Product Manager",
    empProfile: "https://i.pravatar.cc/150?img=5",
  },
  {
    id: 6,
    firstName: "Frank",
    lastName: "Nguyen",
    email: "frank.nguyen@fakemail.com",
    department: "Engineering",
    role: "Backend Developer",
    empProfile: "https://i.pravatar.cc/150?img=6",
  },
  {
    id: 7,
    firstName: "Grace",
    lastName: "Kim",
    email: "grace.kim@fakemail.com",
    department: "Design",
    role: "UX Designer",
    empProfile: "https://i.pravatar.cc/150?img=7",
  },
  {
    id: 8,
    firstName: "Henry",
    lastName: "Adams",
    email: "henry.adams@fakemail.com",
    department: "Engineering",
    role: "DevOps Engineer",
    empProfile: "https://i.pravatar.cc/150?img=8",
  },
  {
    id: 9,
    firstName: "Isabelle",
    lastName: "Lopez",
    email: "isabelle.lopez@fakemail.com",
    department: "Customer Success",
    role: "Support Lead",
    empProfile: "https://i.pravatar.cc/150?img=9",
  },
  {
    id: 10,
    firstName: "Jack",
    lastName: "Owen",
    email: "jack.owen@fakemail.com",
    department: "Sales",
    role: "Sales Executive",
    empProfile: "https://i.pravatar.cc/150?img=10",
  },
  {
    id: 11,
    firstName: "Katherine",
    lastName: "Wilson",
    email: "katherine.wilson@fakemail.com",
    department: "Engineering",
    role: "Full Stack Developer",
    empProfile: "https://i.pravatar.cc/150?img=11",
  },
  {
    id: 12,
    firstName: "Liam",
    lastName: "Brown",
    email: "liam.brown@fakemail.com",
    department: "Marketing",
    role: "Digital Marketing Specialist",
    empProfile: "https://i.pravatar.cc/150?img=12",
  },
  {
    id: 13,
    firstName: "Mia",
    lastName: "Davis",
    email: "mia.davis@fakemail.com",
    department: "Human Resources",
    role: "Recruiter",
    empProfile: "https://i.pravatar.cc/150?img=13",
  },
  {
    id: 14,
    firstName: "Noah",
    lastName: "Miller",
    email: "noah.miller@fakemail.com",
    department: "Finance",
    role: "Financial Analyst",
    empProfile: "https://i.pravatar.cc/150?img=14",
  },
  {
    id: 15,
    firstName: "Olivia",
    lastName: "Taylor",
    email: "olivia.taylor@fakemail.com",
    department: "Product",
    role: "Product Designer",
    empProfile: "https://i.pravatar.cc/150?img=15",
  },
  {
    id: 16,
    firstName: "Paul",
    lastName: "Anderson",
    email: "paul.anderson@fakemail.com",
    department: "Engineering",
    role: "QA Engineer",
    empProfile: "https://i.pravatar.cc/150?img=16",
  },
  {
    id: 17,
    firstName: "Quinn",
    lastName: "Martinez",
    email: "quinn.martinez@fakemail.com",
    department: "Design",
    role: "UI Designer",
    empProfile: "https://i.pravatar.cc/150?img=17",
  },
  {
    id: 18,
    firstName: "Rachel",
    lastName: "Robinson",
    email: "rachel.robinson@fakemail.com",
    department: "Customer Success",
    role: "Customer Success Manager",
    empProfile: "https://i.pravatar.cc/150?img=18",
  },
  {
    id: 19,
    firstName: "Samuel",
    lastName: "Clark",
    email: "samuel.clark@fakemail.com",
    department: "Sales",
    role: "Sales Manager",
    empProfile: "https://i.pravatar.cc/150?img=19",
  },
  {
    id: 20,
    firstName: "Tina",
    lastName: "Rodriguez",
    email: "tina.rodriguez@fakemail.com",
    department: "Engineering",
    role: "Mobile Developer",
    empProfile: "https://i.pravatar.cc/150?img=20",
  },
  {
    id: 21,
    firstName: "Uma",
    lastName: "Lewis",
    email: "uma.lewis@fakemail.com",
    department: "Marketing",
    role: "Brand Manager",
    empProfile: "https://i.pravatar.cc/150?img=21",
  },
  {
    id: 22,
    firstName: "Victor",
    lastName: "Walker",
    email: "victor.walker@fakemail.com",
    department: "Human Resources",
    role: "HR Coordinator",
    empProfile: "https://i.pravatar.cc/150?img=22",
  },
  {
    id: 23,
    firstName: "Wendy",
    lastName: "Hall",
    email: "wendy.hall@fakemail.com",
    department: "Finance",
    role: "Payroll Specialist",
    empProfile: "https://i.pravatar.cc/150?img=23",
  },
  {
    id: 24,
    firstName: "Xavier",
    lastName: "Young",
    email: "xavier.young@fakemail.com",
    department: "Product",
    role: "Product Owner",
    empProfile: "https://i.pravatar.cc/150?img=24",
  },
  {
    id: 25,
    firstName: "Yara",
    lastName: "King",
    email: "yara.king@fakemail.com",
    department: "Engineering",
    role: "Data Engineer",
    empProfile: "https://i.pravatar.cc/150?img=25",
  }
];

// Available departments for form dropdown
export const departments = [
  "Engineering",
  "Marketing", 
  "Human Resources",
  "Finance",
  "Product",
  "Design",
  "Customer Success",
  "Sales"
];

// Available roles for form dropdown
export const roles = [
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile Developer",
  "DevOps Engineer",
  "QA Engineer",
  "Data Engineer",
  "Content Strategist",
  "Digital Marketing Specialist",
  "Brand Manager",
  "HR Manager",
  "Recruiter",
  "HR Coordinator",
  "Accountant",
  "Financial Analyst",
  "Payroll Specialist",
  "Product Manager",
  "Product Designer",
  "Product Owner",
  "UX Designer",
  "UI Designer",
  "Support Lead",
  "Customer Success Manager",
  "Sales Executive",
  "Sales Manager"
];
